UR5E:
  ROBOT_IP: "192.168.1.100"
  LOG_RATE_HZ: 50
  PRIMARY_PORT: 30001
  SECONDARY_PORT: 30002
  REALTIME_PORT: 30003

DATA:
  EXCITING_TRAJ_FILE: "/home/hamid/projects/system_id_ur5e/data/traj/exciting_traj_test.csv"